# Generated by Django 4.1.7 on 2023-04-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_product_image_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
