# Generated by Django 4.1.7 on 2023-04-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_accessories_bottoms_shoes_tops_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tops',
            new_name='Accessory',
        ),
        migrations.RenameModel(
            old_name='Bottoms',
            new_name='Bottom',
        ),
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Top',
        ),
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='bottom',
            options={'verbose_name_plural': 'Bottoms'},
        ),
        migrations.AlterModelOptions(
            name='shoe',
            options={'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterModelOptions(
            name='top',
            options={'verbose_name_plural': 'Tops'},
        ),
    ]
