# Generated by Django 4.1.7 on 2023-04-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_remove_orderitem_product_orderitem_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accessory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.accessory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bottom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bottom'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shoe'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.top'),
        ),
    ]
