# Generated by Django 4.1.7 on 2023-04-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_accessory_orderitem_bottom_orderitem_shoe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='top',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shoe',
        ),
    ]
