# Generated by Django 4.1.7 on 2023-04-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_product_rename_top_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bottom',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.DeleteModel(
            name='Top',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
