# Generated by Django 4.1.7 on 2023-04-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='prov',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
